import json
from textwrap import dedent, indent

from models import ClassifierConfig
from ml_runtime import BUILTIN_DATASET_NAMES, get_builtin_dataset_script_spec, normalize_model_params


def _json_literal(value):
    return json.dumps(value, ensure_ascii=True, indent=4)


def _build_models_config(models: list[ClassifierConfig]) -> str:
    normalized = [{"id": model.id, "params": normalize_model_params(model.id, model.params)} for model in models]
    return _json_literal(normalized)


def generate_fusion_calculator_export_code(fusion_method: str, sources: list) -> tuple[str, str]:
    normalized_sources = [
        {
            "name": source.name,
            "masses": {str(key): float(value) for key, value in source.masses.items()},
        }
        for source in sources
    ]

    script = "\n\n".join(
        [
            "# Generated by FusionLab. Minimal runnable export.",
            "from evidencelib import Frame",
            "\n".join(
                [
                    f"FUSION_METHOD = {fusion_method!r}",
                    f"SOURCES = {_json_literal(normalized_sources)}",
                ]
            ),
            dedent(
                """
                def build_frame():
                    labels = []
                    seen = set()
                    for source in SOURCES:
                        for hypothesis in source["masses"]:
                            if hypothesis not in seen:
                                seen.add(hypothesis)
                                labels.append(hypothesis)
                    atoms = [f"h{i}" for i in range(len(labels))]
                    frame = Frame.dst(atoms)
                    label_to_atom = dict(zip(labels, atoms))
                    atom_to_label = dict(zip(atoms, labels))
                    return frame, label_to_atom, atom_to_label


                def build_belief_mass(frame, label_to_atom, source):
                    masses = {
                        frame.atom(label_to_atom[hypothesis]): float(mass)
                        for hypothesis, mass in source["masses"].items()
                        if abs(float(mass)) > 1e-9
                    }
                    total = sum(masses.values())
                    if abs(total - 1.0) <= 1e-6 and total > 1e-9:
                        masses = {prop: mass / total for prop, mass in masses.items()}
                    else:
                        missing = 1.0 - total
                        if missing > 1e-9:
                            masses[frame.total] = missing
                    return frame.mass(masses)


                def render_result(fused, atom_to_label):
                    result = {}
                    for hypothesis, mass in fused.items():
                        if not hypothesis:
                            key = "empty"
                        else:
                            labels = [
                                atom_to_label.get(atom, atom)
                                for atom in fused.frame.atoms
                                if hypothesis.intersects(fused.frame.atom(atom))
                            ]
                            key = "|".join(labels) if labels else str(hypothesis)
                        result[key] = mass
                    return result


                def main():
                    frame, label_to_atom, atom_to_label = build_frame()
                    belief_masses = [build_belief_mass(frame, label_to_atom, source) for source in SOURCES]
                    first, *rest = belief_masses

                    if FUSION_METHOD == "conjunctive":
                        fused = first.conjunctive(*rest)
                    elif FUSION_METHOD == "dsmc":
                        fused = first.dsmc(*rest)
                    elif FUSION_METHOD == "smets":
                        fused = first.smets(*rest)
                    elif FUSION_METHOD == "dempster":
                        fused = first.dempster(*rest)
                    elif FUSION_METHOD == "yager":
                        fused = first.yager(*rest)
                    elif FUSION_METHOD == "dsmh":
                        fused = first.dsmh(*rest)
                    elif FUSION_METHOD == "dubois_prade":
                        fused = first.dubois_prade(*rest)
                    elif FUSION_METHOD == "pcr5":
                        if len(belief_masses) != 2:
                            raise ValueError("PCR5 accepts exactly two sources in evidencelib. Use PCR6 for three or more sources.")
                        fused = first.pcr5(rest[0])
                    elif FUSION_METHOD == "pcr6":
                        fused = first.pcr6(*rest)
                    else:
                        raise ValueError(f"Unknown fusion method: {FUSION_METHOD}")

                    conflict = fused.conflict
                    result = render_result(fused, atom_to_label)
                    print("Done.")
                    print("Fusion method:", FUSION_METHOD)
                    print("Result masses:", result)
                    print("Conflict:", conflict)


                if __name__ == "__main__":
                    main()
                """
            ).strip(),
        ]
    ).strip() + "\n"

    return script, f"fusion_export_{fusion_method}.py"


def _build_builtin_imports(dataset_imports: list[str]) -> str:
    lines = [
        "import numpy as np",
        "from itertools import combinations",
        "from sklearn.base import clone",
        "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score",
        "from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split",
        "from sklearn.pipeline import Pipeline",
        "from sklearn.preprocessing import StandardScaler",
        "from sklearn.svm import SVC",
        "from sklearn.neighbors import KNeighborsClassifier",
        "from sklearn.naive_bayes import GaussianNB",
        "from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, ExtraTreesClassifier",
        "from sklearn.linear_model import LogisticRegression",
        "from sklearn.tree import DecisionTreeClassifier",
        "from sklearn.neural_network import MLPClassifier",
        *dataset_imports,
        "",
        "from evidencelib import Frame",
    ]
    return "\n".join(lines)


def _build_uploaded_imports() -> str:
    return "\n".join(
        [
            "import csv",
            "import numpy as np",
            "from itertools import combinations",
            "from sklearn.base import clone",
            "from sklearn.compose import ColumnTransformer",
            "from sklearn.metrics import accuracy_score, f1_score, precision_score, recall_score, roc_auc_score",
            "from sklearn.model_selection import StratifiedKFold, cross_val_predict, train_test_split",
            "from sklearn.pipeline import Pipeline",
            "from sklearn.preprocessing import FunctionTransformer, OneHotEncoder, StandardScaler",
            "from sklearn.svm import SVC",
            "from sklearn.neighbors import KNeighborsClassifier",
            "from sklearn.naive_bayes import GaussianNB",
            "from sklearn.ensemble import GradientBoostingClassifier, RandomForestClassifier, ExtraTreesClassifier",
            "from sklearn.linear_model import LogisticRegression",
            "from sklearn.tree import DecisionTreeClassifier",
            "from sklearn.neural_network import MLPClassifier",
            "",
            "from evidencelib import Frame",
        ]
    )


def _build_classifier_function() -> str:
    return dedent(
        """
        def build_model(model_id, params):
            if model_id == "svm":
                return Pipeline([
                    ("scaler", StandardScaler()),
                    ("clf", SVC(probability=True, kernel=params["kernel"], C=params["C"], random_state=42)),
                ])
            if model_id == "knn":
                return Pipeline([
                    ("scaler", StandardScaler()),
                    ("clf", KNeighborsClassifier(n_neighbors=params["n_neighbors"])),
                ])
            if model_id == "naive_bayes":
                return GaussianNB(var_smoothing=params["var_smoothing"])
            if model_id == "gradient_boosting":
                return GradientBoostingClassifier(
                    n_estimators=params["n_estimators"],
                    learning_rate=params["learning_rate"],
                    random_state=42,
                )
            if model_id == "rf":
                return Pipeline([
                    ("scaler", StandardScaler()),
                    ("clf", RandomForestClassifier(
                        n_estimators=params["n_estimators"],
                        max_depth=params["max_depth"],
                        random_state=42,
                    )),
                ])
            if model_id == "logistic_regression":
                return Pipeline([
                    ("scaler", StandardScaler()),
                    ("clf", LogisticRegression(C=params["C"], max_iter=params["max_iter"], random_state=42)),
                ])
            if model_id == "decision_tree":
                return DecisionTreeClassifier(max_depth=params["max_depth"], random_state=42)
            if model_id == "extra_trees":
                return ExtraTreesClassifier(n_estimators=params["n_estimators"], random_state=42)
            if model_id == "mlp":
                hidden = (params["hidden_layer_1"],) if params["hidden_layer_2"] <= 0 else (params["hidden_layer_1"], params["hidden_layer_2"])
                return Pipeline([
                    ("scaler", StandardScaler()),
                    ("clf", MLPClassifier(hidden_layer_sizes=hidden, max_iter=params["max_iter"], random_state=42)),
                ])
            raise ValueError(f"Unknown model: {model_id}")


        def build_training_model(model_id, params, preprocessor=None):
            model = build_model(model_id, params)
            if preprocessor is None:
                return model
            return Pipeline([
                ("preprocessor", clone(preprocessor)),
                ("model", model),
            ])
        """
    ).strip()


def _build_fusion_helpers() -> str:
    return dedent(
        """
        def build_frame(labels):
            atoms = [f"h{i}" for i in range(len(labels))]
            frame = Frame.dst(atoms)
            label_to_atom = dict(zip(labels, atoms))
            atom_to_label = dict(zip(atoms, labels))
            return frame, label_to_atom, atom_to_label


        def proba_to_bba(frame, label_to_atom, proba_row, labels):
            masses = {
                frame.atom(label_to_atom[label]): float(prob)
                for label, prob in zip(labels, proba_row)
                if abs(float(prob)) > 1e-9
            }
            total = sum(masses.values())
            if total <= 1e-9:
                masses = {frame.atom(label_to_atom[label]): 1.0 / len(labels) for label in labels}
            else:
                masses = {prop: mass / total for prop, mass in masses.items()}
            return frame.mass(masses)


        def align_proba(model, X, labels):
            raw = model.predict_proba(X)
            aligned = np.zeros((len(X), len(labels)), dtype=float)
            local_labels = [str(label) for label in model.classes_]
            for i, label in enumerate(local_labels):
                if label in labels:
                    aligned[:, labels.index(label)] = raw[:, i]
            return aligned


        def average_singleton_scores(sample_bbas, labels, label_to_atom):
            scores = np.zeros(len(labels), dtype=float)
            for i, label in enumerate(labels):
                scores[i] = sum(float(bba.mass(bba.frame.atom(label_to_atom[label]))) for bba in sample_bbas) / len(sample_bbas)
            total = float(scores.sum())
            if total > 1e-15:
                scores /= total
            else:
                scores[:] = 1.0 / max(len(labels), 1)
            return scores


        def average_pairwise_conflict(sample_bbas):
            if len(sample_bbas) < 2:
                return None

            total = 0.0
            pairs = 0
            for i, left in enumerate(sample_bbas[:-1]):
                for right in sample_bbas[i + 1:]:
                    pairs += 1
                    for h1, m1 in left.items():
                        for h2, m2 in right.items():
                            if not (h1 & h2):
                                total += float(m1) * float(m2)

            return total / pairs if pairs else None


        def pignistic_scores(fused, labels, atom_to_label):
            raw = fused.pignistic()
            scores = {label: 0.0 for label in labels}
            for atom, value in raw.items():
                label = atom_to_label.get(atom, atom)
                if label in scores:
                    scores[label] = float(value)
            return scores


        def fuse_sample(sample_bbas, labels, label_to_atom, atom_to_label, fusion_method):
            first, *rest = sample_bbas
            if fusion_method == "conjunctive":
                fused = first.conjunctive(*rest)
            elif fusion_method == "dsmc":
                fused = first.dsmc(*rest)
            elif fusion_method == "smets":
                fused = first.smets(*rest)
            elif fusion_method == "dempster":
                try:
                    fused = first.dempster(*rest)
                except Exception as exc:
                    if "conflict" not in str(exc).lower():
                        raise
                    scores = average_singleton_scores(sample_bbas, labels, label_to_atom)
                    return labels[int(np.argmax(scores))], scores, 1.0
            elif fusion_method == "yager":
                fused = first.yager(*rest)
            elif fusion_method == "dsmh":
                fused = first.dsmh(*rest)
            elif fusion_method == "dubois_prade":
                fused = first.dubois_prade(*rest)
            elif fusion_method == "pcr5":
                if len(sample_bbas) != 2:
                    raise ValueError("PCR5 accepts exactly two sources in evidencelib. Use PCR6 for three or more sources.")
                fused = first.pcr5(rest[0])
            elif fusion_method == "pcr6":
                fused = first.pcr6(*rest)
            else:
                raise ValueError(f"Unknown fusion method: {fusion_method}")

            conflict = fused.conflict
            score_map = pignistic_scores(fused, labels, atom_to_label)
            scores = np.array([score_map[label] for label in labels], dtype=float)
            total = float(scores.sum())
            if total > 1e-15:
                scores /= total
            else:
                scores = average_singleton_scores(sample_bbas, labels, label_to_atom)
            predicted_label = labels[int(np.argmax(scores))]

            return predicted_label, scores, conflict


        def calculate_metrics(y_true, y_pred, y_score=None):
            metrics = {
                "accuracy": float(accuracy_score(y_true, y_pred)),
                "precision": float(precision_score(y_true, y_pred, average="weighted", zero_division=0)),
                "recall": float(recall_score(y_true, y_pred, average="weighted", zero_division=0)),
                "f1_score": float(f1_score(y_true, y_pred, average="weighted", zero_division=0)),
                "roc_auc": None,
            }
            if y_score is None or len(set(y_true)) < 2:
                return metrics
            try:
                if y_score.ndim == 1:
                    metrics["roc_auc"] = float(roc_auc_score(y_true, y_score))
                elif y_score.shape[1] == 2:
                    metrics["roc_auc"] = float(roc_auc_score(y_true, y_score[:, 1]))
                else:
                    metrics["roc_auc"] = float(roc_auc_score(y_true, y_score, multi_class="ovr", average="weighted"))
            except ValueError:
                metrics["roc_auc"] = None
            return metrics
        """
    ).strip()


def _build_run_block(dataset_loader: str) -> str:
    run_block = dedent(
        """
        def evaluate_holdout(X, y, labels, preprocessor):
            X_train, X_eval, y_train, y_eval = train_test_split(
                X,
                y,
                test_size=0.25,
                random_state=42,
                stratify=y,
            )

            model_probabilities = []
            model_predictions = []
            model_metrics = []

            for model_cfg in MODELS:
                model = build_training_model(model_cfg["id"], model_cfg["params"], preprocessor)
                model.fit(X_train, y_train)
                proba = align_proba(model, X_eval, labels)
                pred = np.asarray([str(label) for label in model.predict(X_eval)], dtype=object)
                model_probabilities.append(proba)
                model_predictions.append(pred)
                model_metrics.append((model_cfg["id"], calculate_metrics(y_eval, pred, proba)))

            return y_eval, model_probabilities, model_predictions, model_metrics


        def evaluate_cross_validation(X, y, labels, preprocessor):
            if len(X) < CV_FOLDS * 2:
                raise ValueError(f"Need at least {CV_FOLDS * 2} samples for {CV_FOLDS}-fold cross-validation.")

            cv = StratifiedKFold(n_splits=CV_FOLDS, shuffle=True, random_state=42)
            model_probabilities = []
            model_predictions = []
            model_metrics = []

            for model_cfg in MODELS:
                model = build_training_model(model_cfg["id"], model_cfg["params"], preprocessor)
                try:
                    proba = cross_val_predict(model, X, y, cv=cv, method="predict_proba", n_jobs=1)
                except Exception as exc:
                    raise ValueError(f"Cross-validation failed for model '{model_cfg['id']}': {exc}") from exc
                pred = np.asarray([labels[int(i)] for i in np.argmax(proba, axis=1)], dtype=object)
                model_probabilities.append(proba)
                model_predictions.append(pred)
                model_metrics.append((model_cfg["id"], calculate_metrics(y, pred, proba)))

            return y, model_probabilities, model_predictions, model_metrics


        def evaluate_fusion(model_probabilities, labels):
            frame, label_to_atom, atom_to_label = build_frame(labels)
            fused_predictions = []
            fused_scores = []
            total_conflict = 0.0
            conflict_count = 0

            for row_idx in range(len(model_probabilities[0])):
                sample_bbas = [proba_to_bba(frame, label_to_atom, proba[row_idx], labels) for proba in model_probabilities]
                predicted_label, scores, conflict = fuse_sample(sample_bbas, labels, label_to_atom, atom_to_label, FUSION_METHOD)
                fused_predictions.append(predicted_label)
                fused_scores.append(scores)
                if conflict is not None:
                    total_conflict += float(conflict)
                    conflict_count += 1

            avg_conflict = total_conflict / conflict_count if conflict_count > 0 else None
            return np.asarray(fused_predictions, dtype=object), np.asarray(fused_scores), avg_conflict


        def main():
            X, y, preprocessor = load_dataset()
            labels = sorted({str(label) for label in y})
            if USE_CROSS_VALIDATION:
                evaluation_mode = "cv_oof"
                y_eval, model_probabilities, model_predictions, model_metrics = evaluate_cross_validation(X, y, labels, preprocessor)
            else:
                evaluation_mode = "holdout"
                y_eval, model_probabilities, model_predictions, model_metrics = evaluate_holdout(X, y, labels, preprocessor)

            fused_predictions, fused_scores, avg_conflict = evaluate_fusion(model_probabilities, labels)
            fusion_metrics = calculate_metrics(y_eval, fused_predictions, fused_scores)

            print("Done.")
            print("Evaluation mode:", evaluation_mode)
            print("Models:", [model_cfg["id"] for model_cfg in MODELS])
            print("Fusion:", FUSION_METHOD)
            print("Model metrics:", model_metrics)
            print("Fusion metrics:", {**fusion_metrics, "conflict": avg_conflict})
            print("First fused predictions:", fused_predictions[:10].tolist())


        if __name__ == "__main__":
            main()
        """
    ).strip()
    return f"{dataset_loader}\n\n\n{run_block}"


def generate_builtin_export_code(
    dataset_id: str,
    models: list[ClassifierConfig],
    fusion_method: str,
    use_cross_validation: bool,
    cv_folds: int,
) -> tuple[str, str]:
    dataset_name = BUILTIN_DATASET_NAMES.get(dataset_id, dataset_id)
    dataset_spec = get_builtin_dataset_script_spec(dataset_id)
    dataset_body = indent(dataset_spec["body"], "    ")
    dataset_loader = "\n".join(
        [
            "def load_dataset():",
            dataset_body,
            "    y = np.asarray([str(label) for label in y], dtype=object)",
            "    return X, y, None",
        ]
    )

    script = "\n\n".join(
        [
            "# Generated by FusionLab. Minimal runnable export.",
            _build_builtin_imports(dataset_spec["imports"]),
            "\n".join(
                [
                    f"DATASET_NAME = {dataset_name!r}",
                    f"FUSION_METHOD = {fusion_method!r}",
                    f"USE_CROSS_VALIDATION = {bool(use_cross_validation)!r}",
                    f"CV_FOLDS = {int(cv_folds)!r}",
                    f"MODELS = {_build_models_config(models)}",
                ]
            ),
            _build_classifier_function(),
            _build_fusion_helpers(),
            _build_run_block(dataset_loader),
        ]
    ).strip() + "\n"

    return script, f"mlfusion_export_{dataset_id}.py"


def generate_uploaded_export_code(
    dataset_name: str,
    original_filename: str,
    target_column: str,
    feature_columns: list[str],
    feature_types: dict[str, str],
    models: list[ClassifierConfig],
    fusion_method: str,
    use_cross_validation: bool,
    cv_folds: int,
) -> tuple[str, str]:
    script = "\n\n".join(
        [
            "# Generated by FusionLab. Minimal runnable export.",
            "# Set CSV_PATH to your local dataset file before running.",
            _build_uploaded_imports(),
            "\n".join(
                [
                    f"DATASET_NAME = {dataset_name!r}",
                    f"CSV_PATH = {'YOUR_DATASET_PATH/' + original_filename!r}",
                    f"TARGET_COLUMN = {target_column!r}",
                    f"FEATURE_COLUMNS = {_json_literal(feature_columns)}",
                    f"FEATURE_TYPES = {_json_literal(feature_types)}",
                    f"FUSION_METHOD = {fusion_method!r}",
                    f"USE_CROSS_VALIDATION = {bool(use_cross_validation)!r}",
                    f"CV_FOLDS = {int(cv_folds)!r}",
                    f"MODELS = {_build_models_config(models)}",
                ]
            ),
            _build_classifier_function(),
            _build_fusion_helpers(),
            _build_run_block(
                dedent(
                    """
                    def load_dataset():
                        with open(CSV_PATH, newline="", encoding="utf-8-sig") as csv_file:
                            rows = list(csv.DictReader(csv_file))

                        y = np.asarray([str(row[TARGET_COLUMN]) for row in rows], dtype=object)
                        X_rows = []
                        for row in rows:
                            X_rows.append([
                                float(row[column]) if FEATURE_TYPES[column] == "numeric" else str(row[column])
                                for column in FEATURE_COLUMNS
                            ])
                        X = np.asarray(X_rows, dtype=object)

                        numeric_indices = [
                            i for i, column in enumerate(FEATURE_COLUMNS)
                            if FEATURE_TYPES[column] == "numeric"
                        ]
                        categorical_indices = [
                            i for i, column in enumerate(FEATURE_COLUMNS)
                            if FEATURE_TYPES[column] != "numeric"
                        ]
                        transformers = []
                        if numeric_indices:
                            transformers.append(("numeric", FunctionTransformer(lambda values: np.asarray(values, dtype=float)), numeric_indices))
                        if categorical_indices:
                            transformers.append(("categorical", OneHotEncoder(handle_unknown="ignore", sparse_output=False), categorical_indices))

                        preprocessor = ColumnTransformer(transformers=transformers, sparse_threshold=0)
                        return X, y, preprocessor
                    """
                ).strip(),
            ),
        ]
    ).strip() + "\n"

    stem = original_filename.rsplit(".", 1)[0] if "." in original_filename else original_filename
    safe_stem = stem.replace("/", "_").replace("\\", "_").replace(" ", "_").lower() or "custom_dataset"
    return script, f"mlfusion_export_{safe_stem}.py"
